all:
	gcc Pipe1.c -o printer
	gcc PrimeProcessor.c -o processor
	
primes:
	./printer | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor | ./processor
